# Generated by Django 3.1.5 on 2021-01-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
